services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  System25\T3sponsors\:
    resource: '../Classes/*'
    exclude: ['../Classes/Model/*']

  System25\T3sponsors\Frontend\Filter\FormFilter:
    public: true
